FROM eclipse-temurin:21-jdk-alpine AS build

WORKDIR /app
COPY . .

RUN chmod +x scripts/build.sh \
    && scripts/build.sh


FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY --from=build /app/build/duoforge-lobby.jar /app/duoforge-lobby.jar

ENV PORT=80

EXPOSE 80

# Fail during build instead of crashing after deployment
RUN java --list-modules | grep -q "jdk.httpserver"

CMD ["java", "--add-modules", "jdk.httpserver", "-jar", "/app/duoforge-lobby.jar"]