FROM eclipse-temurin:21-jdk-alpine AS build

WORKDIR /app
COPY . .

RUN chmod +x scripts/build.sh \
    && scripts/build.sh


FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY --from=build /app/build/duoforge-lobby.jar /app/duoforge-lobby.jar

ENV PORT=80

EXPOSE 80

# Build ke waqt verify karega ke Java exact location par available hai
RUN test -x /opt/java/openjdk/bin/java \
    && /opt/java/openjdk/bin/java -version

# "java" ki jagah absolute executable path
CMD ["/opt/java/openjdk/bin/java", "--add-modules", "jdk.httpserver", "-jar", "/app/duoforge-lobby.jar"]